### ISSUE TITLE
Error during authentication

### ISSUE THREAD

**Issue by gleich** [LinusS1/Scrapple#12]
While trying to connect my slack account I get the following error:

![Screen Shot 2021-01-10 at 5 04 21 PM](https://user-images.githubusercontent.com/43759105/104136720-e55fdf80-5365-11eb-94f3-4bff877683fc.png)

**Comment by LinusSkucas** [comment]
Hmm, you might be trying to authorize the app in a different workspace. Check to make sure that you’re authorizing it with Hack Club.

**Comment by gleich** [comment]
Ahhh. That was it. Thanks for the quick response!
