### ISSUE TITLE
Scrapple couldn't be installed

### ISSUE THREAD

**Issue by aaryanporwal** [LinusS1/Scrapple#8]
Getting this error when connecting scrapple to slack:
![image](https://user-images.githubusercontent.com/54525904/95075945-b286c980-072e-11eb-8fe3-dac983ca4f74.png)

https://api.slack.com/scopes/remote_files:write

**Comment by LinusSkucas** [comment]
Thanks, I'll look into it. In the meantime you can just delete that in the url if you want scrapple to install: It won't harm anything.

**Comment by aaryanporwal** [comment]
It worked after I removed those permissions from the URL!
